### ISSUE TITLE
如何集成bean-searcher

### ISSUE THREAD

**Issue by LYPgithub-ceo** [ejlchina/bean-searcher#26]
grails 5.1.2如何集成bean-searcher
grom如何在子项目中共享

**Comment by ejlchina** [comment]
直接添加 最新版本的 `bean-searcher-boot-starter` 依赖就 集成好了
如果希望 Bean Searcher 可以复用 Grails 的 domain，需要在 application.yml 中添加一下配置（因为 Grails 会在运行时为 domain 添加一个属性，这里需要将它忽略）：
```yml
bean-searcher:
    sql:
        default-mapping:
            ignore-fields: org_grails_datastore_gorm_GormValidateable__errors
```
